# Generated by Django 5.1.1 on 2024-09-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
    ]
